name: .NET Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # 安装 .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # 编译整个项目
    - name: Build the solution
      run: |
        msbuild -t:restore
        msbuild /p:Configuration=Release /p:Platform="Any CPU"
      env:
        Configuration: ${{ matrix.configuration }}
